name: p_comic
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  http: ^1.2.2
  sqflite: ^2.3.3
  sqflite_common_ffi_web: ^0.4.2
  path: ^1.9.0
  flutter_html: ^3.0.0-beta.2
  timeago: ^3.7.0
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
